### ISSUE TITLE
The changelog keep taking all commits

### ISSUE THREAD

**Issue by danielgefen** [lob/generate-changelog#14]
The scenario is that I'm doing some commits (lets say commits `docs(A): [commit message for A]` and `docs(B): [commit message for B]`), and them I'm running:
```
changelog -M && git add CHANGELOG.md && git commit -M 'updated CHANGELOG.md' && npm version major
```

Then I'm making more commits (lets say commits `docs(C): [commit message for C]` and `docs(D): [commit message for D]`), and them I'm running the same command again.

The changelog output that I'm getting is:
##### Documentation Changes

* **D:**
  * [commit message for D]

* **C:**
  * [commit message for C]

* **B:**
  * [commit message for B]

* **A:**
  * [commit message for A]

##### Documentation Changes

* **B:**
  * [commit message for B]

* **A:**
  * [commit message for A]

I would expect A and B not to appear in versoin 2.0.0. How does `generate-changlog` know where to cut the commits between version? How can I make sure that commits from the previous version won't be part of the next version?

**Comment by robinjoseph08** [comment]
Hey @danielgefen,

So I just tried that sequence of events on a clean repo and it looks to have worked:

```sh
$ mkdir generate-changelog-test
$ cd generate-changelog-test
$ git init
Initialized empty Git repository in /private/tmp/generate-changelog-test/.git/
$ npm init
# ...
$ touch a
$ git add a
$ git commit -m "docs(A): [commit message for A]"
[master (root-commit) 7100f2f] docs(A): [commit message for A]
1 file changed, 0 insertions(+), 0 deletions(-)
create mode 100644 a
$ touch b
$ git add b
$ git commit -m "docs(B): [commit message for B]"
[master ee8caaa] docs(B): [commit message for B]
1 file changed, 0 insertions(+), 0 deletions(-)
create mode 100644 b
$ changelog -M && git add CHANGELOG.md && git commit -m 'updated CHANGELOG.md' && npm version major
[master 1c4da38] updated CHANGELOG.md
1 file changed, 7 insertions(+)
create mode 100644 CHANGELOG.md
v1.0.0
$ touch c
$ git add c
$ git commit -m "docs(C): [commit message for C]"
[master cda8048] docs(C): [commit message for C]
1 file changed, 0 insertions(+), 0 deletions(-)
create mode 100644 c
$ touch d
$ git add d
$ git commit -m "docs(D): [commit message for D]"
[master b7e980d] docs(D): [commit message for D]
1 file changed, 0 insertions(+), 0 deletions(-)
create mode 100644 d
$ changelog -M && git add CHANGELOG.md && git commit -m 'updated CHANGELOG.md' && npm version major
[master 29a4eda] updated CHANGELOG.md
1 file changed, 7 insertions(+)
v2.0.0
$ cat CHANGELOG.md
## 2.0.0 (2017-4-12)

##### Documentation Changes

* **D:** [commit message for D] (b7e980dd)
* **C:** [commit message for C] (cda80487)

## 1.0.0 (2017-4-12)

##### Documentation Changes

* **B:** [commit message for B] (ee8caaac)
* **A:** [commit message for A] (7100f2fd)
```

One guess I have for why it might not have worked for you depends on whether you ran `changelog` twice on the same machine or on two different machines. This tool relies heavily on [git tags](https://github.com/lob/generate-changelog/blob/v1.1.0/lib/git.js#L15-L23), so it's important that they're kept consistent. When you run `npm version [major|minor|patch]`, it does [several things for you](https://docs.npmjs.com/cli/version). One thing it does is create a new git tag. This is great since it'll help deliminate between versions, but one thing you have to remember is to push those newly created tags with `git push origin --tags`. If you don't push up the tags, they won't exist on anybody else's computer if they run `changelog`, which means it won't know to stop after commits A and B. That's why we [recommend adding `git push --tags` to the chained commands](https://github.com/lob/generate-changelog/blob/v1.1.0/README.md#recommended).

If you're not entirely sure, you can run `git tag` on the machines you ran `changelog` on and see if there's a discrepancy. If there isn't, can you try running the same commands I ran above in your temp directory and see if you get the same results? There might be an edge case that we haven't considered.

Thanks!

**Comment by robinjoseph08** [comment]
Hey @danielgefen I'm gonna close this issue for now since you haven't replied for a while, but feel free to comment again if you're still facing the problem!
