### ISSUE TITLE
Add comitter id to changelog

### ISSUE THREAD

**Issue by pke** [lob/generate-changelog#5]
Would it be possible to include the commiter of a changeset in the changelog?

**Comment by robinjoseph08** [comment]
Thanks for the suggestion @pke!

Since we care more about the commit itself rather than the author and we work in a very code-review-centric environment, we probably won't be adding a reference to the committer in the changelog. Once a PR/commit goes through code review and gets merged into master, we all take responsibility of the code change.

If you really need to know the author, you can always click the link of the commit to view all of the details of it (the diff, the author, the date, etc).

**Comment by pke** [comment]
So a PR with a new CLI param `--user` to include the user name will not be considered?

**Comment by yharaskrik** [comment]
Hey @robinjoseph08 I would second what @pke is saying here. I would be more than happy to work on a PR for it.
