### ISSUE TITLE
Ignore commit messages that do not adhere to the format

### ISSUE THREAD

**Issue by pke** [lob/generate-changelog#6]
I am getting an "undefined" printed in the changelog, cause the commit message was and old one not following the format required by `generate-changelog`

```
##### Bug Fixes

* **undefined:** remove reference...
```

That was generated from "Fix: remove reference..."
So it was missing the category capture group.
So https://github.com/lob/generate-changelog/blob/master/lib/git.js#L50 should look like this:
`commit.category = parsed[3] || "";`

Why do you capture a 3rd capture group that includes the `catagory` in braces `(category)`. Its not used anywhere.

How about this match pattern?
https://regex101.com/r/tB8sV4/2

It captures 3/2 groups: type/[category]/subject

**Comment by robinjoseph08** [comment]
Hey @pke! Thanks for creating an issue!

The reason that third capture group exists isn't to use it later, but to make the `(category)` part of the commit message optional. That's why it matches `Fix: test`. We could use the match pattern that you have in the regex101.com link, but then `category` will have the parenthesis in it, which isn't desired. We could do an additional `commit.category = parsed[3].replace(/[\(\)]/g, '');`, but we thought it was a bit cleaner to do it all using capture groups.

As for the `undefined` category, I agree, it shouldn't be printing `* **undefined:**`. But instead of defaulting to the empty string, I think the change should go [in the writing logic](https://github.com/lob/generate-changelog/blob/master/lib/writer.js#L68-L77). We can't just use the empty string because that would output `* **:** remove reference...` when it should just output `* remove reference...`.

Feel free to put up a PR to fix this issue, but if you can't, we'll try to tackle it as soon as we can!

**Comment by pke** [comment]
Ok, how about this regex?

https://regex101.com/r/tB8sV4/9

No additional group, relaxed spacing fixes and strict start-words.
